### PR TITLE
Switch to now node builder, add options, and remove landing page

### LINKED ISSUE #1: Deploy setup for Now v2
I have literally no idea how to deploy this to Now v2. There are two apps: 1. image microservice built with `micro` and 2. a Gatsby site for the landing page.

- Routes with `/:foreground/:background` should go to the image service
- All other routes should go to the Gatsby site

### PR DESCRIPTION
**Pull request by jxnblk**
Fixes #1 HT @ynnoj

### CODE REVIEW

**Comment by ynnoj** [comment]
@jxnblk Opted to just kill the Gatsby site for now?

**Comment by jxnblk** [comment]
Yeah, I think the readme will work for now. Also, I'm so sorry, I totally missed that you had an open PR already 😬 – just noodled around in between other tasks and was trying to make sure I understood how all the Zeit now stuff worked

**Comment by ynnoj** [comment]
No problem. Hopefully I helped clear some things up for you 😅

**Comment by jxnblk** [comment]
No, it was *super* helpful – thanks for helping out with this!

**Pull request merged**
